# List of bootstrap nodes to connect to
bootstrap:
  - "/ip4/34.219.111.49/tcp/30333/p2p/QmTricoBZbRr1HG6FQykEwpfqJpj2MB2bv4ATNim82k12F"

# Private key only used for p2p communications. null means generate one
p2p_secret_key: null

# name, Chain to run (dev/local)
chain: "dev"

# Authority key, null means don't attempt to produce blocks
aura_secret_key: null
